### ISSUE TITLE
Why'd you stop?

### ISSUE THREAD

**Issue by yardenac** [sandy-bultena/Euclid#2]
Your videos and material on books 1-7 are really helpful and I would love to see books 8-13 also! Thank you. :)

**Comment by sandy-bultena** [comment]
Hi, thank you for your interest.

I got side tracked for a bit, but I do plan on finishing them. 

Right now I am in the middle of a school semester, so it will have to wait until after school ends.

I do truly appreciate your kind words.

Sandy

**Comment by sandy-bultena** [comment]
I'm back

**Comment by sandy-bultena** [comment]
Book 8 will be done over the summer.  Already half way there
